# Generated by Django 5.0.2 on 2024-05-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_comment_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
