# Generated by Django 5.0.2 on 2024-05-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_remove_job_ongiong_manpower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='open_manpower',
        ),
        migrations.AddField(
            model_name='job',
            name='ongiong_manpower',
            field=models.IntegerField(default=0),
        ),
    ]
