# Generated by Django 5.0.2 on 2024-05-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0006_remove_job_open_manpower_job_ongiong_manpower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='ongiong_manpower',
            new_name='ongoing_manpower',
        ),
    ]
